version: '3.4'
services:
  deluge:
    container_name: deluge
    image: 'linuxserver/deluge:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '${ROOT}/hdd2/auto_media/downloads:/downloads'
      - '${ROOT}/config/deluge:/config'
  jackett:
    container_name: jackett
    image: 'linuxserver/jackett:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${ROOT}/downloads/torrent-blackhole:/downloads'
      - '${ROOT}/config/jackett:/config'
  sonarr:
    container_name: sonarr
    image: 'linuxserver/sonarr:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${ROOT}/config/sonarr:/config'
      - '${ROOT}/hdd1/TV_Shows:/tv'
      - '${ROOT}/hdd2/auto_media/downloads:/downloads'
  radarr:
    container_name: radarr
    image: 'linuxserver/radarr:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${ROOT}/config/radarr:/config'
      - '${ROOT}/hdd1/Movies:/movies'
      - '${ROOT}/hdd2/auto_media/downloads:/downloads'
  plex-server:
    container_name: plex-server
    image: 'plexinc/pms-docker:latest'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ}'
    network_mode: host
    volumes:
      - '${ROOT}/config/plex/db:/config'
      - '${ROOT}/config/plex/transcode:/transcode'
      - '${ROOT}/hdd1:/data'
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - UMASK_SET=022
    volumes:
      - '${ROOT}/config/bazarr:/config'
      - '${ROOT}/hdd1/Movies:/movies'
      - '${ROOT}/hdd1/TV_Shows:/tv'
  pyload:
    image: lscr.io/linuxserver/pyload-ng
    container_name: pyload-ng
    environment:
      - 'PUID=$(PUID)'
      - 'PGID=$(PGID)'
      - 'TZ=${TZ}'
    volumes:
      - '/path/to/pyload/config:/config'
      - '/path/to/downloads:/downloads'
    ports:
      - '8000:8000'
    restart: unless-stopped
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - 'PUID=$(PUID)'
      - 'PGID=$(PGID)'
      - 'TZ=${TZ}'
    volumes:
      - '${ROOT}/config/bazarr:/config'
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
